name: CI

on:
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          workdir: ${{ matrix.path }}
          path: ./.venv
          key: venv-${{ hashFiles('uv.lock') }}

      - name: Install the project dependencies
        run: uv sync --frozen
        working-directory: ${{ matrix.path }}

      - uses: pre-commit/action@v3.0.1

  packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
        - packages/manim_anki
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          workdir: ${{ matrix.path }}
          path: ./.venv
          key: venv-${{ hashFiles('uv.lock') }}

      - name: Install the project dependencies
        run: uv sync --frozen
        working-directory: ${{ matrix.path }}

  decks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - ./decks/linear_algebra
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          workdir: ${{ matrix.path }}
          path: ./.venv
          key: venv-${{ hashFiles('uv.lock') }}

      - name: Install the project dependencies
        run: uv sync --frozen
        working-directory: ${{ matrix.path }}
